server:
  port:8080

spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  h2:
    console:
      enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
  #      password:
        data : classpath:data-h2.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # 시작하면서 도메인 객체 구성과 DB의 스키마를 비교해 필요한 테이블이나 컬럼이 없을 때 도메인 객체에 맞춰 DB 스키마를 변경
    properties.hibernate.hbm2ddl.auto: update
    # JPA가 실행하는 쿼리를 Console 출력
    showSql: true
    # i18n 경로 추가 및 인코딩 설정
  messages:
    basename: i18n/exception
    encoding: UTF-8